language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli karma forever bower --production --loglevel warn
  - bower install --production --quiet
  - forever start karma-server.js
  # used for Firefox and Chrome to work
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - forever stop karma-server.js
